services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_dev
    ports:
      - 5432:5432
    volumes:
      - /tmp/pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
