services:
  app:
    build: .
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/todo_dev
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - "/app/node_modules" # Prevents override of node_modules between host and container
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_dev
    ports:
      - 5432:5432
    volumes:
      - /tmp/pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
