name: Release code

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Next release version (e.g., 1.2.3)"
        required: true

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get Last Release tag
        id: lasttag
        run: |
          echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Generate changelog
        id: changelog
        run: |
          changelog=$(git log ${{ steps.lasttag.outputs.tag }}..HEAD --pretty=format:'- %s')
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo $changelog >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Update CHANGELOG.md
        run: |
          echo "## ${{ github.event.inputs.version }} - $(date +'%Y-%m-%d')" > temp.md
          echo "${{ steps.changelog.outputs.changelog }}" >> temp.md
          echo "" >> temp.md
          cat CHANGELOG.md >> temp.md
          mv temp.md CHANGELOG.md

      - name: Commit changelog
        run: |
          git add CHANGELOG.md
          git commit -m "docs: Update changelog to release ${{ github.event.inputs.version }}"
          git push origin

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          body: ${{ steps.changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}

      - name: Deploy to Render
        run: |
          curl ${{ secrets.RENDER_DEPLOY_HOOK }}
