name: Release code

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Next release version (e.g., 1.2.3)"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get Last Release tag
        id: lasttag
        run: |
          tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Generate changelog
        id: changelog
        run: |
          if [ -z "${{ steps.lasttag.outputs.tag }}" ]; then
            changelog=$(git log --pretty=format:'- %s')
          else
            changelog=$(git log ${{ steps.lasttag.outputs.tag }}..HEAD --pretty=format:'- %s')
          fi
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo $changelog >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Update CHANGELOG.md
        run: |
          echo "## ${{ github.event.inputs.version }} - $(date +'%Y-%m-%d')" > temp.md
          echo "${{ steps.changelog.outputs.changelog }}" >> temp.md
          echo "" >> temp.md
          cat CHANGELOG.md >> temp.md
          mv temp.md CHANGELOG.md

      - name: Commit changelog
        run: |
          git add CHANGELOG.md
          git commit -m "docs: Update changelog to release ${{ github.event.inputs.version }}"
          git push origin

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          body: ${{ steps.changelog.outputs.changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Render
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}
